/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import grailsclient.jwt.APIError
import grailsclient.jwt.FileJwtStorage
import grailsclient.jwt.RestExecutor

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
		
    }
}
